---
title: "HW 01"
author: "Meredith Jean-Baptiste"
format: 
  html:
    embed-resources: true
execute: 
  warning: false
  message: false
  error: false
toc: true
---

## 0 - Setup

```{r setup}
if (!require("pacman")) 
  install.packages("pacman")

# use this line for installing/loading
# pacman::p_load() 

devtools::install_github("tidyverse/dsbox")
```

## 1 - Road traffic accidents in Edinburgh

```{r Road traffic accidents in Edinburgh_Question-1}
# load packages
library(tidyverse)
library(here)
library(countdown)

# set theme for ggplot2
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 14))

# set width of code output
options(width = 65)

# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7,        # 7" width
  fig.asp = 0.618,      # the golden ratio
  fig.retina = 3,       # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300             # higher dpi, sharper image
)

#load the dataset
accidents <- read_csv("~/Documents/Meredith Documents/1 Mer docs/1 PhD/5 SPRING 2025/INFO 526 DATA VISUALIZATION/HOMEWORK/hw_01_merjb/data/accidents.csv")

#mutate day_of_the_week to weekend/ weekday: 
#NOTE: none of these mutates worked as hoped for
#NOTE: after multiple attempts to mutate, the correct approach was found however the title for weekday/ weekend is on the side.
accidents_wrangle <- accidents |>
  #mutate(weekend = day_of_week == "Saturday", "Sunday") |>
  #mutate(weekday = day_of_week == "Monday", "Tuesday", "Wednesday", "Thursday", #"Friday")|>
 mutate(day_week = if_else(day_of_week == "Saturday" | day_of_week == "Sunday", "Weekend", "Weekday"))
  
# Make plot
accidents_wrangle |>
  ggplot(aes(time,fill = severity))+
  geom_density(alpha = 0.5)+
  theme_light()+
  #I finally figured out facets after completing question 4 on this homework but could not solve the label issue.
  facet_grid(day_week~.)+
  scale_fill_manual(values = c("purple","deepskyblue3","yellow")) +
   labs(
    x = "Time of day",
    y = "Density",
     title = "Number of accidents throughout the day",
    subtitle = "By day of week and severity",
    caption = "Source: Road traffic accidents in Edinburgh, 2018,\n R Programming 101: Create a boxplot using R programming with the ggplot package,\n R Programming 101: Advanced ggplot - using facets (2023) https://www.youtube.com/watch?v=sxknFa1rprY")

```

## 2 - NYC marathon winners

```{r NYC Marathon winners_Question-2}
# load packages
library(tidyverse)
library(here)
library(countdown)

# set theme for ggplot2
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 14))

# set width of code output
options(width = 65)

# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7,        # 7" width
  fig.asp = 0.618,      # the golden ratio
  fig.retina = 3,       # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300             # higher dpi, sharper image
)

# load the dataset
nyc_marathon <- read_csv("~/Documents/Meredith Documents/1 Mer docs/1 PhD/5 SPRING 2025/INFO 526 DATA VISUALIZATION/HOMEWORK/hw_01_merjb/data/nyc_marathon.csv")

# a. Histogram
nyc_marathon|>
  drop_na(time_hrs) |>
  ggplot(aes(time_hrs)) +
  geom_histogram(binwidth = 0.02, fill = "cornsilk4")+
  theme_minimal()+
  labs(
    x = "Times",
    y = NULL,
     title = "NYC Marathon Winners 1970 - 2020",
    caption = "Source: OpenIntro 25.0 https://openintrostat.github.io/openintro/reference/nyc_marathon.html\nR Programming 101")

# This histogram is skewed to the right. There appear to be two peaks of times and the data is not normally distributed.

# a. Boxplot
nyc_marathon|>
  drop_na(time_hrs) |>
  ggplot(aes(,time_hrs)) +
  geom_boxplot() +
  theme_classic() +
  stat_boxplot(geom = 'errorbar', width = 0.2)+
  labs(
    title = "NYC Marathon Winners 1970 - 2020",
    x = NULL,
    y = "Times",
    caption = "Source: OpenIntro 25.0 https://openintrostat.github.io/openintro/reference/nyc_marathon.html\nR Programming 101: Create a boxplot using R programming with the ggplot package")
# The median for this boxplot is ~2.40 hrs, with the 25%ile at ~2.15 hrs and the 75%ile at ~2.48 hrs and some outliers at over 2.85hrs and >3hrs. We cannot observe this level of data in the histogram.

# b. Boxplot by Gender
nyc_marathon|>
  drop_na(time_hrs) |>
  ggplot(aes(division, time_hrs, fill = division)) +
  geom_boxplot() +
  theme_classic() +
  scale_fill_manual(values = c("cornsilk4","deepskyblue3")) +
  stat_boxplot(geom = 'errorbar', width = 0.2)+
  labs(
    y = "Times",
    x = "Division",
    title = "NYC Marathon Winners 1970 - 2020",
    caption = "Source: OpenIntro 25.0 \nhttps://openintrostat.github.io/openintro/reference/nyc_marathon.html\nR Programming 101: Create a boxplot using R programming with the ggplot package")+
   theme(
    legend.position = c(0.9, 0.9),
    legend.box.background = element_rect(fill = "white",
                                         color = "white"),
  )
# This boxplot is now much more clear in terms of race times by gender. It is clear that the marathon times differ between Men and Women.

# c. Boxplot updated
nyc_marathon|>
  drop_na(time_hrs) |>
  ggplot(aes(division, time_hrs, fill = division)) +
  geom_boxplot() +
  coord_flip()+
  theme_classic() +
  scale_fill_manual(values = c("cornsilk4","deepskyblue3")) +
  stat_boxplot(geom = 'errorbar', width = 0.2)+
  labs(
    y = "Times",
    x = "Division",
    title = "NYC Marathon Winners 1970 - 2020",
    caption = "Source: OpenIntro 25.0 \nhttps://openintrostat.github.io/openintro/reference/nyc_marathon.html\nR Programming 101: Create a boxplot using R programming with the ggplot package")+
   theme(
    legend.position = c(0.9, 0.9),
    legend.box.background = element_rect(fill = "white",
                                         color = "white"),
  )

#There was not much redundancy in this second iteration of the boxplot, however to update change the data to ink ratio, if we look at the data vertically, it becomes easier to read.

# d. Marathon times over the years by gender
nyc_marathon|>
  drop_na(time_hrs) |>
  ggplot(aes(year, time_hrs, color = division)) +
  geom_point(show.legend = FALSE) +
  geom_line(linewidth = 1) +
  theme_classic() +
  scale_color_manual(values = c("cornsilk4","deepskyblue3")) +
  labs(
    y = "Time",
    x = "Year",
    title = "NYC Marathon Winners 1970 - 2020",
    caption = "Source: OpenIntro 25.0 \nhttps://openintrostat.github.io/openintro/reference/nyc_marathon.html\nR Programming 101: Create a boxplot using R programming with the ggplot package")+
  theme(
    legend.position = c(0.9, 0.9),
    legend.box.background = element_rect(fill = "white",
                                         color = "white"),
  )
# In this line graph, we see that over the years, both men and women have gotten faster, however it is clear that Men run faster times than women and that the lines never cross nor overlap. Additionally we see that in 2020, the marathon time was slower than the past 4 decades, likely due to the virtual events held due to the Covid-19 pandemic.

```

## 3 - US counties

```{r US counties_Question-3}
#Source: R/data-county.R
#install.packages("openintro")

# I was unsuccessful loading the dataset "County" for this Homework 01 question 3 but continued to try and with the correct packages, was successful.

# Load libraries
library(tidyverse)
library(here)
library(countdown)
library(openintro)

#a.The following code [below] does not make sense for the median of the boxplots. If we plotted on the x-axis, the median education on top of the boxplot of the smoking ban, by the median household income on the y-axis,  this would not make sense for the smoking compared to the population as depicted in the boxplot.
#ggplot(county) +
 # geom_point(aes(x = median_edu, y = median_hh_income)) +
  #geom_boxplot(aes(x = smoking_ban, y = pop2017))


#b. The second plot of the " facet_grid (.~median_edu) " is easier to read as the data is stacked side by side, making the labels easier to read and the homeownership x poverty for each category of ecuation far cleaner.

#c. 
#Plot A: 
county %>% 
   drop_na(homeownership) %>% 
  drop_na(poverty)|>
ggplot() +
  geom_point(aes(x = homeownership, y = poverty))+
  scale_color_manual(values = c("black")) +
  labs(x = "homeownership",
        y = "poverty", 
        title = "Plot A")+
  theme_minimal()

#Plot B:
county %>% 
  drop_na(homeownership) %>% 
  drop_na(poverty)|>
ggplot(aes(x = homeownership,
           y = poverty)) +
  geom_point()+
  geom_smooth(se = FALSE, size = 0.8, color = "blue")+
  scale_color_manual(values = c("black")) +
  labs(x = "homeownership",
        y = "poverty", 
        title = "Plot B")+
  theme_minimal()

#Plot C:
county %>% 
  drop_na(homeownership) %>% 
  drop_na(poverty)|>
ggplot(aes(x = homeownership, 
           y = poverty,
           color = metro,
           line = metro))+
  geom_point()+
  scale_color_manual(values = c("black", "black")) +
  geom_smooth(se = FALSE, size = 0.8, color = "green")+
  labs(x = "homeownership",
        y = "poverty", 
        title = "Plot C")+
  theme_minimal()

#Plot D:
county %>% 
  drop_na(homeownership) %>% 
  drop_na(poverty)|>
ggplot(aes(x = homeownership, 
           y = poverty,
           color = metro,
           line = metro))+
  geom_point()+
  scale_color_manual(values = c("black", "black")) +
  geom_smooth(se = FALSE, size = 0.8, color = "blue")+
  labs(x = "homeownership",
        y = "poverty", 
        title = "Plot D")+
  theme_minimal()

#Plot E:
county %>% 
  drop_na(homeownership) %>% 
  drop_na(poverty)|>
ggplot(aes(x = homeownership,
           y = poverty,
           color = metro,
           linetype = metro,
           showlegend = TRUE)) +
  geom_point(aes(x = homeownership, y = poverty, color = metro, size = 2))+
  geom_smooth(se = FALSE, size = 0.8, color = "blue")+
#  scale_color_manual(values = c("deepskyblue","salmon")) +
  labs(x = "homownership",
        y = "poverty", 
        title = "Plot E")+
  theme_minimal()

#Plot F:
county %>% 
  drop_na(homeownership) %>% 
  drop_na(poverty)|>
ggplot(aes(x = homeownership,
           y = poverty,
           color = metro)) +
  geom_point(size = 2)+
  geom_smooth(se = FALSE, size = 0.8, showlegend = FALSE)+
#  scale_color_manual(values = c("deepskyblue","salmon")) +
  labs(x = "homownership",
        y = "poverty", 
        title = "Plot F")+
  theme_minimal()

#Plot G:
county %>% 
  drop_na(homeownership) %>% 
  drop_na(poverty)|>
ggplot(aes(x = homeownership,
           y = poverty,
           color = metro)) +
  geom_point(size = 2)+
  geom_smooth(se = FALSE, size = 0.8, color = "blue", showlegend = FALSE)+
 # scale_color_manual(values = c("deepskyblue","salmon")) +
  labs(x = "homownership",
        y = "poverty", 
        title = "Plot G")+
  theme_minimal()


#Plot H:
county %>% 
  drop_na(homeownership) %>% 
  drop_na(poverty)|>
ggplot(aes(x = homeownership,
           y = poverty,
           color = metro)) +
  geom_point(size = 2, showlegend = FALSE)+
  #scale_color_manual(values = c("salmon","deepskyblue")) +
  labs(x = "homownership",
        y = "poverty", 
        title = "Plot H")+
  theme_minimal()


```

## 4 - Rental apartments in SF

```{r Rental apartments SF_Question-4}
#setup
if (!require("pacman")) 
  install.packages("pacman")

# use this line for installing/loading
#pacman::p_load() 
#load the library 
library(readr)
library(tidyverse)
library(here)
library(countdown)

# set theme for ggplot2
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 14))

# set width of code output
options(width = 65)

# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7,        # 7" width
  fig.asp = 0.618,      # the golden ratio
  fig.retina = 3,       # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300             # higher dpi, sharper image
)

# load the dataset
 credit <- read_csv("data/credit.csv")
# make the comparison plot
 credit |>
   mutate (student = if_else(student == "No","student: No", "student: Yes"))|>
   mutate(married = if_else(married == "No", "married: No", "married: Yes"))|>
   ggplot(aes(x = income, 
              y = balance, 
              color = student,
              shape = student))+
   geom_point(size = 2, alpha = 0.4, show.legend = FALSE)+
   geom_smooth(method = "lm", se = FALSE, size = 0.8, show.legend = FALSE)+
  #scale_y_continuous(labels = label_dollar(big.mark = ",")) +
  #scale_x_continuous(labels = label_dollar(suffix = "K")) +
   facet_grid(student~married)+
   scale_color_manual(values = c("blue","red")) +
   labs(x = "Income",
        y = "Credit card balance", 
        caption = "Source: R Programming 101: Advanced ggplot - using facets (2023) https://www.youtube.com/watch?v=sxknFa1rprY")+
   theme_bw()
  
# a. The relationship between income and credit card balance appears to be a positive relationship across all categories: married/ not married/ student/ not student. As income increases, credit card balance also increases.
 
# b. Whether someone is married or a student Unmarried people (in general) seem to have lower salaries than married people, with married people who are not students have both the highest salaries and the highest credit card balance.
 
 # c. 
 # Updated comparison plot
 credit |>
   mutate(
     credit_utilization = ((balance/limit)*100)
   ) |>
   mutate (student = if_else(student == "No","student: No", "student: Yes"))|>
   mutate(married = if_else(married == "No", "married: No", "married: Yes"))|>
   ggplot(aes(x = income, 
              y = credit_utilization, 
              color = student,
              shape = student))+
   geom_point(size = 2, alpha = 0.4, show.legend = FALSE)+
   geom_smooth(method = "lm", se = FALSE, size = 0.8, show.legend = FALSE)+
  #scale_y_continuous(labels = label_dollar(big.mark = ",")) +
  #scale_x_continuous(labels = label_dollar(suffix = "K")) +
   facet_grid(student~married)+
   scale_color_manual(values = c("blue","red")) +
   labs(x = "Income",
        y = "Credit card balance", 
        caption = "Source: R Programming 101: Advanced ggplot - using facets (2023) https://www.youtube.com/watch?v=sxknFa1rprY")+
   theme_bw()

 # d. Based on the plot from part (c) we now see that when we examine the relationship between Income and credit utilizaiton, there is a negative relationship (if the student is not married) or a slope of zero if the student is married. When compared to non-students, the relationship between income and credit utilizaiton is positive. 
```

## 5 - Napoleon’s march.

```{r Napoleons march_Question-5}
#load dataset
napoleon <- readRDS("~/Documents/Meredith Documents/1 Mer docs/1 PhD/5 SPRING 2025/INFO 526 DATA VISUALIZATION/HOMEWORK/hw_01_merjb/data/napoleon.rds")

#Troop data
    data(Minard.troops, package="HistData")
    str(Minard.troops)
#Cities Data
    data(Minard.cities, package="HistData")
    str(Minard.cities)
#Temperature data
    data(Minard.temp, package="HistData")
    str(Minard.temp)

#load libraries
library(tidyverse)
library(lubridate)
library(ggmap)
library(ggrepel)
library(gridExtra)
library(pander)
library(dplyr)


#start the basic ggplot
ggplot(Minard.troops, aes(x = long, y = lat, group = group)) +
  geom_path(aes(size = survivors, color = direction, group = group), lineend = "round")+
  scale_color_manual("direction", values = c("skyblue3", "salmon3"),
                     labels = c("Advance", "Retreat"))+
  theme_linedraw()+
  theme(
    legend.position = c(0.9, 0.15),
    legend.key.height = unit(0.01, 'cm'),
    legend.text=element_text(size=rel(0.7)),
    legend.box.background = element_rect(fill = "white",
                                         color = "white"))+
   labs(x = "Longitude",
        y = "Latitude", 
        caption = "Source: GitHub shakir-flash (2023) https://github.com/shakir-flash/Napoleons-March-Minard-Visualization\n Michael Friendly (2018) http://euclid.psych.yorku.ca/www/psy6135/tutorials/Minard.html\n Zach Bobbitt (2020) https://www.statology.org/ggplot2-legend-size/")
  
# At the bottom of the graphic my first citation was where I was able to upload the data to complete this assignment. 
#The second citation is where I found clear explanation of the basic steps such as how to apply color based on direction. 
# I only used code for this exercise that I could clearly explain. 
#I tried to change the size of the legend and found how to do this using my third citation on here. 
#I am happy with the location on the lower right hand corner and learned this placement from our class lectures. 
#After uploading the data, I was able to create an asthetic in ggplot using the Minard.troops organization of the three tables. 
#The x-axis is the longitude and the y-axis is the latitude and I added labels to explain as such. 
#I used the geom_path aesthetic to account for the survivor size and values of the colors which I manually chose using the scale_color_manual by the direction variable. 
#I learned how to manually choose colors from the class lectures. I tried several colors adding a number following the name, before decideing upon these. 

```
